language: python
python:
  - "3.5"
  - "3.6"

env:
  - PILLOW=4.0.0
  - PILLOW=5.0.0
  - PILLOW=5.*

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# See https://github.com/travis-ci/travis-ci/issues/9815
# On Python 3.7 we test only the first and the latest version 5 of Pillow
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      env: PILLOW=5.0.0
    - python: 3.7
      dist: xenial
      sudo: true
      env: PILLOW=5.*

install:
  - pip install pytest Pillow==$PILLOW
  - pip install -e .
script:
  - pytest tests/
